name: Android CI

#on: [push]
on:
  push:
    branches:
      - buildTest

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      OPENAI_API: ${{ secrets.OPENAI_API }}

    steps:
    - uses: actions/checkout@v2
    - run: echo $OPENAI_API
