# .github/workflows/deploy.yml
name: CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Pull Repo
      - uses: actions/checkout@v3

      # Github Secrets에서 API Key 받아온 후 .env 파일에 추가
      - run: |
          echo "REACT_APP_API_KEY=${{secrets.OPENAI_API}}" >> .env
          echo "REACT_APP_DOMAIN=${{secrets.DOMAIN}}" >> .env
          echo "REACT_APP_PROJECT_ID=${{secrets.PROJECT_ID}}" >> .env
          echo "REACT_APP_BUCKET=${{secrets.BUCKET}}" >> .env
          echo "REACT_APP_SENDER_ID=${{secrets.SENDER_ID}}" >> .env
          echo "REACT_APP_APP_ID=${{secrets.APP_ID}}" >> .env
          echo "REACT_APP_MEASUREMENT_ID=${{secrets.MEASUREMENT_ID}}" >> .env
      - run: cat .env

      - run: npm install
      - run: npm run build
